/* //vendor/sprd/proprietories-source/ril/libril/ril_ims_unsol_commands.h
**
** Copyright (C) 2016 Spreadtrum Communications Inc.
*/
    {RIL_EXT_UNSOL_VIDEOPHONE_CODEC, responseInts, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_DSCI, responseDSCI, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_STRING, responseString, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_REMOTE_MEDIA, responseInts, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_MM_RING, responseInts, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_RELEASING, responseString, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_RECORD_VIDEO, responseInts, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_MEDIA_START, responseInts, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_ECC_NETWORKLIST_CHANGED, responseString, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_RAU_SUCCESS, responseVoid, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_CLEAR_CODE_FALLBACK, responseVoid, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_RIL_CONNECTED, responseVoid, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SIMLOCK_STATUS_CHANGED, responseVoid, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SIMLOCK_SIM_EXPIRED, responseInts, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_BAND_INFO, responseString, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SWITCH_PRIMARY_CARD, responseInts, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SIM_PS_REJECT, responseVoid, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SETUP_DATA_FOR_CP, responseVoid, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SIMMGR_SIM_STATUS_CHANGED, responseVoid, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_RADIO_CAPABILITY_CHANGED, responseVoid, WAKE_PARTIAL},
