/* //vendor/sprd/proprietories-source/ril/libril/ril_ims_unsol_commands.h
**
** Copyright (C) 2016 Spreadtrum Communications Inc.
*/
    {RIL_EXT_UNSOL_VIDEOPHONE_CODEC, radio::videoPhoneCodecInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_DSCI, radio::videoPhoneDSCIInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_STRING, radio::videoPhoneStringInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_REMOTE_MEDIA, radio::videoPhoneRemoteMediaInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_MM_RING, radio::videoPhoneMMRingInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_RELEASING, radio::videoPhoneReleasingInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_RECORD_VIDEO, radio::videoPhoneRecordVideoInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_VIDEOPHONE_MEDIA_START, radio::videoPhoneMediaStartInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_ECC_NETWORKLIST_CHANGED, radio::eccNetworkListChangedInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_RAU_SUCCESS, radio::rauSuccessInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_CLEAR_CODE_FALLBACK, radio::clearCodeFallbackInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_RIL_CONNECTED, radio::extRILConnectedInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SIMLOCK_STATUS_CHANGED, radio::simlockStatusChangedInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SIMLOCK_SIM_EXPIRED, radio::simlockSimExpiredInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_BAND_INFO, radio::bandInfoInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SWITCH_PRIMARY_CARD, radio::switchPrimaryCardInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SIM_PS_REJECT, radio::simPSRejectInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_SIMMGR_SIM_STATUS_CHANGED, radio::simMgrSimStatusChangedInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_RADIO_CAPABILITY_CHANGED, radio::radioCapabilityChangedInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_EARLY_MEDIA, radio::earlyMediaInd, WAKE_PARTIAL},
    {RIL_EXT_UNSOL_IMS_CSFB_VENDOR_CAUSE, radio::IMSCsfbVendorCauseInd, WAKE_PARTIAL},
